# Generated by Django 3.2.16 on 2022-11-06 09:22

from django.db import migrations, models
import tweet.models.tweet


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20221104_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tweet.models.tweet.tweet_file_path),
        ),
    ]
