
version: '3'

services:
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    volumes:
    - ./local/mysql-data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    - MYSQL_ROOT_HOST=*
    - MYSQL_DATABASE=${DB_NAME}
    - MYSQL_USER=${DB_USER}
    - MYSQL_PASSWORD=${DB_PASSWORD}
    - TZ="Asia/Tokyo"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  setup:
    build: .
    env_file:
      - .env
    environment:
    - DB_SECRET_KEY=${DB_SECRET_KEY}
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_HOST=mysql
    command: python -u manage.py migrate --settings=config.settings.production
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
  app:
    build: .
    env_file:
      - .env
    environment:
    - DB_SECRET_KEY=${DB_SECRET_KEY}
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_HOST=mysql
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
    - AWS_STORAGE_REGION=${AWS_STORAGE_REGION}
    - AWS_SES_REGION_NAME=${AWS_SES_REGION_NAME}
    - EMAIL_HOST_USER=${EMAIL_HOST_USER}
    - PRODUCTION_HOSTS=localhost
    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - mysql
      - setup
