FROM amd64/python:3.8-slim as builder

WORKDIR /tmp

RUN pip install --upgrade pip
RUN pip install poetry

COPY pyproject.toml poetry.lock ./

RUN poetry export --without-hashes --dev -f requirements.txt > requirements.txt


FROM amd64/python:3.8-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt update

# for mysqlclient
RUN apt install -y default-libmysqlclient-dev

# for uwsgi
RUN apt install -y gcc

COPY --from=builder /tmp/requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

RUN python manage.py collectstatic --noinput

CMD [ "uwsgi", "--http", "0.0.0.0:80", "--module", "config.wsgi", "--static-map", "/static=./static" ]
