# Generated by Django 2.1 on 2018-08-25 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
