# Generated by Django 3.1.6 on 2021-10-31 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models.auth
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190217_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=32)),
                ('expired_at', models.DateTimeField(default=main.models.auth.gen_expired_at)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthDigit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=main.models.auth.random_digit_code, max_length=6)),
                ('expired_at', models.DateTimeField(default=main.models.auth.gen_expired_at)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
