# Generated by Django 3.1.6 on 2022-11-03 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221104_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInvalid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=15)),
                ('count', models.IntegerField(default=1)),
                ('denied_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
