# Generated by Django 3.1.6 on 2022-11-03 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models.image
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=main.models.image.image_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
